# Generated by Django 5.0.6 on 2024-05-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('descriccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['idmunicipio'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('descriccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['idpais'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.AutoField(primary_key=True, serialize=False)),
                ('descriccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['idprovincia'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('idcorreos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globos.correos')),
                ('idmunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globos.municipio')),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globos.pais')),
                ('idprovincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globos.provincia')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['idpersona'],
            },
        ),
    ]
