# Generated by Django 5.0.6 on 2024-05-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0002_municipio_pais_provincia_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='correos',
            name='activo',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='correos',
            name='codigo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='correos',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
