# Generated by Django 5.0.6 on 2024-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0003_correos_activo_correos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correos',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='correos',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
