# Generated by Django 5.0.6 on 2024-06-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0004_alter_correos_activo_alter_correos_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idcorreos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.correos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='idmunicipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.municipio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='idpais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='idpersona',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='idprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.provincia'),
        ),
    ]
