# Generated by Django 5.0.6 on 2024-06-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0006_alter_persona_idcorreos_alter_persona_idmunicipio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='descriccion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='descriccion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='descriccion',
            new_name='descripcion',
        ),
    ]
