# Generated by Django 5.0.6 on 2024-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0007_rename_descriccion_municipio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pasaporte',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
