# Generated by Django 5.0.6 on 2024-06-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0008_persona_direccion_persona_pasaporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('descripcionProd', models.CharField(choices=[('0', 'Globos'), ('3', 'Cubiertos'), ('1', 'Arcos')], max_length=50)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['idproducto'],
            },
        ),
        migrations.AlterField(
            model_name='correos',
            name='direccion',
            field=models.EmailField(max_length=100),
        ),
    ]
