# Generated by Django 5.0.6 on 2024-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0009_producto_alter_correos_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NArco',
            fields=[
                ('idarco', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('0', 'Globos'), ('1', 'Tela')], max_length=15)),
            ],
            options={
                'verbose_name': 'NArco',
                'verbose_name_plural': 'NArcos',
                'ordering': ['idarco'],
            },
        ),
        migrations.CreateModel(
            name='NBase',
            fields=[
                ('idbase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('2', 'Cilindro'), ('1', 'Cubo'), ('0', 'Corazón')], max_length=15)),
            ],
            options={
                'verbose_name': 'NBase',
                'verbose_name_plural': 'NBases',
                'ordering': ['idbase'],
            },
        ),
        migrations.CreateModel(
            name='NCentromesa',
            fields=[
                ('idcentromesa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('0', 'centromesa1'), ('1', 'centromesa2')], max_length=15)),
            ],
            options={
                'verbose_name': 'NCentromesa',
                'verbose_name_plural': 'NCentromesas',
                'ordering': ['idcentromesa'],
            },
        ),
        migrations.CreateModel(
            name='NCubiertos',
            fields=[
                ('idcubierto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('1', 'Platos'), ('2', 'Servilletas'), ('0', 'vasos')], max_length=15)),
            ],
            options={
                'verbose_name': 'NCubierto',
                'verbose_name_plural': 'NCubiertos',
                'ordering': ['idcubierto'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('3', 'Cubiertos'), ('1', 'Arcos'), ('0', 'Globos')], max_length=50),
        ),
    ]
