# Generated by Django 5.0.6 on 2024-06-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0010_narco_nbase_ncentromesa_ncubiertos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('idcartel', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tamano', models.IntegerField(null=True)),
                ('personalizacion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cartel',
                'verbose_name_plural': 'Carteles',
                'ordering': ['idcartel'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('diaevento', models.CharField(max_length=2, null=True)),
                ('anno', models.CharField(max_length=4, null=True)),
                ('nombparte1', models.CharField(max_length=50, null=True)),
                ('nombparte2', models.CharField(max_length=50, null=True)),
                ('dirlugarevento', models.CharField(max_length=200, null=True)),
                ('precioevento', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['idcontrato'],
            },
        ),
        migrations.CreateModel(
            name='Globos',
            fields=[
                ('idglobos', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('formaglobos', models.CharField(choices=[('4', 'Extragrande'), ('1', 'Mediano'), ('3', 'Grande'), ('0', 'Chiquito')], max_length=15, null=True)),
                ('colorglobos', models.CharField(choices=[('4', 'Amarillo'), ('11', 'Negro'), ('8', 'Púrpura'), ('3', 'Verde'), ('2', 'Rojo'), ('9', 'Marrón'), ('10', 'Gris'), ('5', 'Azul'), ('1', 'Blanco'), ('7', 'Rosa'), ('6', 'Naranja')], max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Globo',
                'verbose_name_plural': 'Globos',
                'ordering': ['idglobos'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('idmes', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(choices=[('8', 'Agosto'), ('5', 'Mayo'), ('9', 'Septiembre'), ('1', 'Enero'), ('6', 'Junio'), ('4', 'Abril'), ('12', 'Diciembre'), ('11', 'Noviembre'), ('10', 'Octubre'), ('7', 'Julio'), ('2', 'Febrero'), ('3', 'Marzo')], max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['idmes'],
            },
        ),
        migrations.CreateModel(
            name='Pinata',
            fields=[
                ('idpinata', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('formapinat', models.CharField(choices=[('0', 'Cuadrado'), ('2', 'Redondo'), ('3', 'Corazón'), ('1', 'Rectangular')], max_length=15, null=True)),
                ('colorpinata', models.CharField(choices=[('4', 'Amarillo'), ('11', 'Negro'), ('8', 'Púrpura'), ('3', 'Verde'), ('2', 'Rojo'), ('9', 'Marrón'), ('10', 'Gris'), ('5', 'Azul'), ('1', 'Blanco'), ('7', 'Rosa'), ('6', 'Naranja')], max_length=15, null=True)),
                ('tematica', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pinata',
                'verbose_name_plural': 'Pinatas',
                'ordering': ['tematica'],
            },
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Flores'), ('2', 'Luminarias'), ('0', 'Globos'), ('3', 'Tela')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Cilindro'), ('0', 'Corazón'), ('3', 'Cilindro medio'), ('1', 'Cubo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('0', 'Adornos'), ('1', 'Dulces')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Platos'), ('2', 'Servilletas'), ('0', 'Vasos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('5', 'Cubiertos'), ('2', 'Cartel'), ('1', 'Arcos'), ('3', 'Piñata'), ('4', 'Centro de mesa'), ('0', 'Globos'), ('6', 'Base')], max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='idcontrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.contrato'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('idbase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.nbase')),
                ('idcartel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.cartel')),
                ('idcentromesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.ncentromesa')),
                ('idcontrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.contrato')),
                ('idcubierto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.ncubiertos')),
                ('idproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.producto')),
                ('idglobos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.globos')),
                ('idpinata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.pinata')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['idevento'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('idcombo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('idproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.producto')),
                ('idevento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.evento')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['idcombo'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='idmes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.mes'),
        ),
    ]
