# Generated by Django 5.0.6 on 2024-06-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0011_cartel_contrato_globos_mes_pinata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correos',
            name='fecharegistro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('8', 'Púrpura'), ('4', 'Amarillo'), ('6', 'Naranja'), ('5', 'Azul'), ('3', 'Verde'), ('10', 'Gris'), ('9', 'Marrón'), ('1', 'Blanco'), ('11', 'Negro'), ('2', 'Rojo'), ('7', 'Rosa')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('0', 'Chiquito'), ('1', 'Mediano'), ('3', 'Grande'), ('4', 'Extragrande')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('11', 'Noviembre'), ('3', 'Marzo'), ('5', 'Mayo'), ('10', 'Octubre'), ('1', 'Enero'), ('6', 'Junio'), ('12', 'Diciembre'), ('7', 'Julio'), ('9', 'Septiembre'), ('2', 'Febrero'), ('8', 'Agosto'), ('4', 'Abril')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Tela'), ('1', 'Flores'), ('2', 'Luminarias'), ('0', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Cilindro'), ('1', 'Cubo'), ('3', 'Cilindro medio'), ('0', 'Corazón')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Dulces'), ('0', 'Adornos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('0', 'Vasos'), ('2', 'Servilletas'), ('1', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('8', 'Púrpura'), ('4', 'Amarillo'), ('6', 'Naranja'), ('5', 'Azul'), ('3', 'Verde'), ('10', 'Gris'), ('9', 'Marrón'), ('1', 'Blanco'), ('11', 'Negro'), ('2', 'Rojo'), ('7', 'Rosa')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('1', 'Rectangular'), ('2', 'Redondo'), ('0', 'Cuadrado'), ('3', 'Corazón')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('6', 'Base'), ('3', 'Piñata'), ('0', 'Globos'), ('4', 'Centro de mesa'), ('1', 'Arcos'), ('2', 'Cartel'), ('5', 'Cubiertos')], max_length=50),
        ),
    ]
