# Generated by Django 5.0.6 on 2024-06-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0013_alter_globos_colorglobos_alter_globos_formaglobos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.IntegerField(choices=[('7', 'Rosa'), ('2', 'Rojo'), ('1', 'Blanco'), ('4', 'Amarillo'), ('10', 'Gris'), ('8', 'Púrpura'), ('9', 'Marrón'), ('3', 'Verde'), ('5', 'Azul'), ('11', 'Negro'), ('6', 'Naranja')], null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.IntegerField(choices=[('1', 'Mediano'), ('3', 'Grande'), ('4', 'Extragrande'), ('0', 'Chiquito')], null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('10', 'Octubre'), ('4', 'Abril'), ('3', 'Marzo'), ('11', 'Noviembre'), ('9', 'Septiembre'), ('2', 'Febrero'), ('5', 'Mayo'), ('12', 'Diciembre'), ('7', 'Julio'), ('8', 'Agosto'), ('1', 'Enero'), ('6', 'Junio')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Tela'), ('2', 'Luminarias'), ('1', 'Flores'), ('0', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('0', 'Corazón'), ('1', 'Cubo'), ('2', 'Cilindro'), ('3', 'Cilindro medio')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Dulces'), ('0', 'Adornos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Servilletas'), ('1', 'Platos'), ('0', 'Vasos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('7', 'Rosa'), ('2', 'Rojo'), ('1', 'Blanco'), ('4', 'Amarillo'), ('10', 'Gris'), ('8', 'Púrpura'), ('9', 'Marrón'), ('3', 'Verde'), ('5', 'Azul'), ('11', 'Negro'), ('6', 'Naranja')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('2', 'Redondo'), ('1', 'Rectangular'), ('3', 'Corazón'), ('0', 'Cuadrado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('6', 'Base'), ('4', 'Centro de mesa'), ('0', 'Globos'), ('3', 'Piñata'), ('2', 'Cartel'), ('1', 'Arcos'), ('5', 'Cubiertos')], max_length=50),
        ),
    ]
