# Generated by Django 5.0.6 on 2024-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0014_alter_globos_colorglobos_alter_globos_formaglobos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('1', 'Blanco'), ('11', 'Negro'), ('5', 'Azul'), ('4', 'Amarillo'), ('10', 'Gris'), ('6', 'Naranja'), ('2', 'Rojo'), ('7', 'Rosa'), ('3', 'Verde'), ('8', 'Púrpura'), ('9', 'Marrón')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('4', 'Extragrande'), ('1', 'Mediano'), ('0', 'Chiquito'), ('3', 'Grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('12', 'Diciembre'), ('11', 'Noviembre'), ('8', 'Agosto'), ('5', 'Mayo'), ('7', 'Julio'), ('6', 'Junio'), ('1', 'Enero'), ('4', 'Abril'), ('2', 'Febrero'), ('9', 'Septiembre'), ('3', 'Marzo'), ('10', 'Octubre')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Luminarias'), ('3', 'Tela'), ('1', 'Flores'), ('0', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Cilindro'), ('1', 'Cubo'), ('3', 'Cilindro medio'), ('0', 'Corazón')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('0', 'Adornos'), ('1', 'Dulces')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Servilletas'), ('0', 'Vasos'), ('1', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('1', 'Blanco'), ('11', 'Negro'), ('5', 'Azul'), ('4', 'Amarillo'), ('10', 'Gris'), ('6', 'Naranja'), ('2', 'Rojo'), ('7', 'Rosa'), ('3', 'Verde'), ('8', 'Púrpura'), ('9', 'Marrón')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('0', 'Cuadrado'), ('1', 'Rectangular'), ('3', 'Corazón'), ('2', 'Redondo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('3', 'Piñata'), ('6', 'Base'), ('5', 'Cubiertos'), ('1', 'Arcos'), ('4', 'Centro de mesa'), ('0', 'Globos'), ('2', 'Cartel')], max_length=50),
        ),
    ]
