# Generated by Django 5.0.6 on 2024-06-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0015_alter_globos_colorglobos_alter_globos_formaglobos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTematica',
            fields=[
                ('idtematica', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(choices=[('3', 'Revelación de sexo'), ('4', 'Baby shawers'), ('6', 'Aniversario de boda'), ('8', 'Día San Valentín'), ('2', 'Boda'), ('9', 'Compromiso'), ('1', 'Cumpleaños'), ('5', 'Graduación'), ('7', '14 de febrero')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ntematica',
                'verbose_name_plural': 'NTematicas',
                'ordering': ['idtematica'],
            },
        ),
        migrations.AddField(
            model_name='globos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globos',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('8', 'Púrpura'), ('10', 'Gris'), ('9', 'Marrón'), ('2', 'Rojo'), ('4', 'Amarillo'), ('6', 'Naranja'), ('3', 'Verde'), ('7', 'Rosa'), ('1', 'Blanco'), ('11', 'Negro'), ('5', 'Azul')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('4', 'Extragrande'), ('3', 'Grande'), ('1', 'Chiquito'), ('2', 'Mediano')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('7', 'Julio'), ('1', 'Enero'), ('12', 'Diciembre'), ('3', 'Marzo'), ('9', 'Septiembre'), ('5', 'Mayo'), ('4', 'Abril'), ('2', 'Febrero'), ('6', 'Junio'), ('8', 'Agosto'), ('10', 'Octubre'), ('11', 'Noviembre')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Flores'), ('4', 'Tela'), ('3', 'Luminarias'), ('1', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Corazón'), ('2', 'Cubo'), ('3', 'Cilindro'), ('4', 'Cilindro medio')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Adornos'), ('2', 'Dulces')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Servilletas'), ('1', 'Vasos'), ('2', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('8', 'Púrpura'), ('10', 'Gris'), ('9', 'Marrón'), ('2', 'Rojo'), ('4', 'Amarillo'), ('6', 'Naranja'), ('3', 'Verde'), ('7', 'Rosa'), ('1', 'Blanco'), ('11', 'Negro'), ('5', 'Azul')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('3', 'Redondo'), ('4', 'Corazón'), ('2', 'Rectangular'), ('1', 'Cuadrado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('2', 'Arcos'), ('1', 'Globos'), ('4', 'Piñata'), ('7', 'Base'), ('6', 'Cubiertos'), ('3', 'Cartel'), ('5', 'Centro de mesa')], max_length=50),
        ),
        migrations.AddField(
            model_name='contrato',
            name='idtematica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.ntematica'),
        ),
    ]
