# Generated by Django 5.0.6 on 2024-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0017_remove_globos_cantidad_remove_globos_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globos',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('11', 'Negro'), ('4', 'Amarillo'), ('7', 'Rosa'), ('2', 'Rojo'), ('3', 'Verde'), ('5', 'Azul'), ('1', 'Blanco'), ('6', 'Naranja'), ('10', 'Gris'), ('9', 'Marrón'), ('8', 'Púrpura')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('4', 'Extragrande'), ('2', 'Mediano'), ('3', 'Grande'), ('1', 'Chiquito')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Abril'), ('6', 'Junio'), ('9', 'Septiembre'), ('10', 'Octubre'), ('3', 'Marzo'), ('12', 'Diciembre'), ('1', 'Enero'), ('5', 'Mayo'), ('8', 'Agosto'), ('7', 'Julio'), ('2', 'Febrero'), ('11', 'Noviembre')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Flores'), ('4', 'Tela'), ('3', 'Luminarias'), ('1', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Cilindro'), ('1', 'Corazón'), ('4', 'Cilindro medio'), ('2', 'Cubo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Servilletas'), ('1', 'Vasos'), ('2', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Cumpleaños'), ('7', '14 de febrero'), ('5', 'Graduación'), ('8', 'Día San Valentín'), ('3', 'Revelación de sexo'), ('4', 'Baby shawers'), ('9', 'Compromiso'), ('2', 'Boda'), ('6', 'Aniversario de boda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('11', 'Negro'), ('4', 'Amarillo'), ('7', 'Rosa'), ('2', 'Rojo'), ('3', 'Verde'), ('5', 'Azul'), ('1', 'Blanco'), ('6', 'Naranja'), ('10', 'Gris'), ('9', 'Marrón'), ('8', 'Púrpura')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('1', 'Cuadrado'), ('2', 'Rectangular'), ('3', 'Redondo'), ('4', 'Corazón')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('5', 'Centro de mesa'), ('1', 'Globos'), ('7', 'Base'), ('4', 'Piñata'), ('3', 'Cartel'), ('6', 'Cubiertos'), ('2', 'Arcos')], max_length=50),
        ),
    ]
