# Generated by Django 5.0.6 on 2024-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0018_globos_cantidad_globos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('4', 'Amarillo'), ('8', 'Púrpura'), ('9', 'Marrón'), ('6', 'Naranja'), ('7', 'Rosa'), ('5', 'Azul'), ('2', 'Rojo'), ('11', 'Negro'), ('1', 'Blanco'), ('10', 'Gris'), ('3', 'Verde')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('3', 'Grande'), ('4', 'Extragrande'), ('2', 'Mediano')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Enero'), ('10', 'Octubre'), ('11', 'Noviembre'), ('3', 'Marzo'), ('4', 'Abril'), ('8', 'Agosto'), ('9', 'Septiembre'), ('6', 'Junio'), ('7', 'Julio'), ('5', 'Mayo'), ('12', 'Diciembre'), ('2', 'Febrero')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Tela'), ('3', 'Luminarias'), ('2', 'Flores'), ('1', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Cubo'), ('4', 'Cilindro medio'), ('1', 'Corazón'), ('3', 'Cilindro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Dulces'), ('1', 'Adornos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Servilletas'), ('2', 'Platos'), ('1', 'Vasos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Baby shawers'), ('3', 'Revelación de sexo'), ('5', 'Graduación'), ('7', '14 de febrero'), ('1', 'Cumpleaños'), ('6', 'Aniversario de boda'), ('9', 'Compromiso'), ('8', 'Día San Valentín'), ('2', 'Boda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('4', 'Amarillo'), ('8', 'Púrpura'), ('9', 'Marrón'), ('6', 'Naranja'), ('7', 'Rosa'), ('5', 'Azul'), ('2', 'Rojo'), ('11', 'Negro'), ('1', 'Blanco'), ('10', 'Gris'), ('3', 'Verde')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('1', 'Cuadrado'), ('4', 'Corazón'), ('2', 'Rectangular'), ('3', 'Redondo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('7', 'Base'), ('1', 'Globos'), ('2', 'Arcos'), ('4', 'Piñata'), ('5', 'Centro de mesa'), ('3', 'Cartel'), ('6', 'Cubiertos')], max_length=50),
        ),
    ]
