# Generated by Django 5.0.6 on 2024-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0020_combo_precio_alter_globos_colorglobos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('10', 'Gris'), ('6', 'Naranja'), ('1', 'Blanco'), ('7', 'Rosa'), ('4', 'Amarillo'), ('3', 'Verde'), ('5', 'Azul'), ('2', 'Rojo'), ('9', 'Marrón'), ('8', 'Púrpura'), ('11', 'Negro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('2', 'Mediano'), ('1', 'Chiquito'), ('4', 'Extragrande'), ('3', 'Grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Marzo'), ('6', 'Junio'), ('11', 'Noviembre'), ('10', 'Octubre'), ('12', 'Diciembre'), ('7', 'Julio'), ('4', 'Abril'), ('1', 'Enero'), ('8', 'Agosto'), ('5', 'Mayo'), ('9', 'Septiembre'), ('2', 'Febrero')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Tela'), ('3', 'Luminarias'), ('1', 'Globos'), ('2', 'Flores')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Corazón'), ('4', 'Cilindro medio'), ('3', 'Cilindro'), ('2', 'Cubo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Dulces'), ('1', 'Adornos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Vasos'), ('2', 'Platos'), ('3', 'Servilletas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('5', 'Graduación'), ('3', 'Revelación de sexo'), ('7', '14 de febrero'), ('2', 'Boda'), ('9', 'Compromiso'), ('8', 'Día San Valentín'), ('1', 'Cumpleaños'), ('6', 'Aniversario de boda'), ('4', 'Baby shawers')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('10', 'Gris'), ('6', 'Naranja'), ('1', 'Blanco'), ('7', 'Rosa'), ('4', 'Amarillo'), ('3', 'Verde'), ('5', 'Azul'), ('2', 'Rojo'), ('9', 'Marrón'), ('8', 'Púrpura'), ('11', 'Negro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinat',
            field=models.CharField(choices=[('4', 'Corazón'), ('1', 'Cuadrado'), ('3', 'Redondo'), ('2', 'Rectangular')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('6', 'Cubiertos'), ('2', 'Arcos'), ('4', 'Piñata'), ('1', 'Globos'), ('5', 'Centro de mesa'), ('7', 'Base'), ('3', 'Cartel')], max_length=50),
        ),
    ]
