# Generated by Django 5.0.6 on 2024-06-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0021_alter_globos_colorglobos_alter_globos_formaglobos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinata',
            name='formapinat',
        ),
        migrations.AddField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('3', 'Redondo'), ('2', 'Rectangular'), ('4', 'Corazón'), ('1', 'Cuadrado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('7', 'Rosa'), ('2', 'Rojo'), ('11', 'Negro'), ('1', 'Blanco'), ('3', 'Verde'), ('5', 'Azul'), ('4', 'Amarillo'), ('10', 'Gris'), ('9', 'Marrón'), ('8', 'Púrpura'), ('6', 'Naranja')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('2', 'Mediano'), ('4', 'Extragrande'), ('3', 'Grande'), ('1', 'Chiquito')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('6', 'Junio'), ('1', 'Enero'), ('8', 'Agosto'), ('11', 'Noviembre'), ('10', 'Octubre'), ('12', 'Diciembre'), ('9', 'Septiembre'), ('5', 'Mayo'), ('3', 'Marzo'), ('4', 'Abril'), ('2', 'Febrero'), ('7', 'Julio')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Luminarias'), ('1', 'Globos'), ('4', 'Tela'), ('2', 'Flores')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Cilindro'), ('2', 'Cubo'), ('4', 'Cilindro medio'), ('1', 'Corazón')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Platos'), ('1', 'Vasos'), ('3', 'Servilletas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Cumpleaños'), ('7', '14 de febrero'), ('9', 'Compromiso'), ('6', 'Aniversario de boda'), ('2', 'Boda'), ('4', 'Baby shawers'), ('8', 'Día San Valentín'), ('5', 'Graduación'), ('3', 'Revelación de sexo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('7', 'Rosa'), ('2', 'Rojo'), ('11', 'Negro'), ('1', 'Blanco'), ('3', 'Verde'), ('5', 'Azul'), ('4', 'Amarillo'), ('10', 'Gris'), ('9', 'Marrón'), ('8', 'Púrpura'), ('6', 'Naranja')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('6', 'Cubiertos'), ('1', 'Globos'), ('2', 'Arcos'), ('7', 'Base'), ('3', 'Cartel'), ('5', 'Centro de mesa'), ('4', 'Piñata')], max_length=50),
        ),
    ]
