# Generated by Django 5.0.6 on 2024-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0022_remove_pinata_formapinat_pinata_formapinata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='idproducto',
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('7', 'Rosa'), ('10', 'Gris'), ('1', 'Blanco'), ('6', 'Naranja'), ('2', 'Rojo'), ('9', 'Marrón'), ('5', 'Azul'), ('3', 'Verde'), ('8', 'Púrpura'), ('4', 'Amarillo'), ('11', 'Negro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('4', 'Extragrande'), ('2', 'Mediano'), ('3', 'Grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('8', 'Agosto'), ('4', 'Abril'), ('5', 'Mayo'), ('1', 'Enero'), ('9', 'Septiembre'), ('12', 'Diciembre'), ('6', 'Junio'), ('10', 'Octubre'), ('7', 'Julio'), ('3', 'Marzo'), ('11', 'Noviembre'), ('2', 'Febrero')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Tela'), ('2', 'Flores'), ('3', 'Luminarias'), ('1', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Corazón'), ('4', 'Cilindro medio'), ('2', 'Cubo'), ('3', 'Cilindro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Adornos'), ('2', 'Dulces')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Vasos'), ('3', 'Servilletas'), ('2', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('5', 'Graduación'), ('4', 'Baby shawers'), ('3', 'Revelación de sexo'), ('8', 'Día San Valentín'), ('9', 'Compromiso'), ('7', '14 de febrero'), ('6', 'Aniversario de boda'), ('2', 'Boda'), ('1', 'Cumpleaños')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('7', 'Rosa'), ('10', 'Gris'), ('1', 'Blanco'), ('6', 'Naranja'), ('2', 'Rojo'), ('9', 'Marrón'), ('5', 'Azul'), ('3', 'Verde'), ('8', 'Púrpura'), ('4', 'Amarillo'), ('11', 'Negro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('4', 'Corazón'), ('3', 'Redondo'), ('1', 'Cuadrado'), ('2', 'Rectangular')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('5', 'Centro de mesa'), ('2', 'Arcos'), ('4', 'Piñata'), ('3', 'Cartel'), ('6', 'Cubiertos'), ('7', 'Base'), ('1', 'Globos')], max_length=50),
        ),
    ]
