# Generated by Django 5.0.6 on 2024-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0023_remove_evento_idproducto_alter_globos_colorglobos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='diaevento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='idmes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('6', 'Naranja'), ('7', 'Rosa'), ('3', 'Verde'), ('5', 'Azul'), ('4', 'Amarillo'), ('9', 'Marrón'), ('2', 'Rojo'), ('11', 'Negro'), ('8', 'Púrpura'), ('1', 'Blanco'), ('10', 'Gris')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('2', 'Mediano'), ('3', 'Grande'), ('4', 'Extragrande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('12', 'Diciembre'), ('4', 'Abril'), ('8', 'Agosto'), ('3', 'Marzo'), ('1', 'Enero'), ('7', 'Julio'), ('2', 'Febrero'), ('9', 'Septiembre'), ('10', 'Octubre'), ('5', 'Mayo'), ('6', 'Junio'), ('11', 'Noviembre')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Flores'), ('1', 'Globos'), ('3', 'Luminarias'), ('4', 'Tela')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Cilindro'), ('4', 'Cilindro medio'), ('1', 'Corazón'), ('2', 'Cubo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Revelación de sexo'), ('8', 'Día San Valentín'), ('1', 'Cumpleaños'), ('4', 'Baby shawers'), ('6', 'Aniversario de boda'), ('9', 'Compromiso'), ('2', 'Boda'), ('7', '14 de febrero'), ('5', 'Graduación')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('6', 'Naranja'), ('7', 'Rosa'), ('3', 'Verde'), ('5', 'Azul'), ('4', 'Amarillo'), ('9', 'Marrón'), ('2', 'Rojo'), ('11', 'Negro'), ('8', 'Púrpura'), ('1', 'Blanco'), ('10', 'Gris')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('2', 'Rectangular'), ('3', 'Redondo'), ('1', 'Cuadrado'), ('4', 'Corazón')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('7', 'Base'), ('1', 'Globos'), ('6', 'Cubiertos'), ('2', 'Arcos'), ('5', 'Centro de mesa'), ('3', 'Cartel'), ('4', 'Piñata')], max_length=50),
        ),
    ]
