# Generated by Django 5.0.6 on 2024-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0024_remove_contrato_anno_remove_contrato_diaevento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('7', 'Rosa'), ('3', 'Verde'), ('11', 'Negro'), ('1', 'Blanco'), ('6', 'Naranja'), ('8', 'Púrpura'), ('2', 'Rojo'), ('10', 'Gris'), ('9', 'Marrón'), ('4', 'Amarillo'), ('5', 'Azul')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('3', 'Grande'), ('2', 'Mediano'), ('1', 'Chiquito'), ('4', 'Extragrande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('10', 'Octubre'), ('4', 'Abril'), ('7', 'Julio'), ('12', 'Diciembre'), ('1', 'Enero'), ('6', 'Junio'), ('11', 'Noviembre'), ('3', 'Marzo'), ('8', 'Agosto'), ('9', 'Septiembre'), ('2', 'Febrero'), ('5', 'Mayo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Cilindro'), ('2', 'Cubo'), ('1', 'Corazón'), ('4', 'Cilindro medio')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Servilletas'), ('1', 'Vasos'), ('2', 'Platos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Revelación de sexo'), ('1', 'Cumpleaños'), ('8', 'Día San Valentín'), ('4', 'Baby shawers'), ('5', 'Graduación'), ('7', '14 de febrero'), ('6', 'Aniversario de boda'), ('9', 'Compromiso'), ('2', 'Boda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('7', 'Rosa'), ('3', 'Verde'), ('11', 'Negro'), ('1', 'Blanco'), ('6', 'Naranja'), ('8', 'Púrpura'), ('2', 'Rojo'), ('10', 'Gris'), ('9', 'Marrón'), ('4', 'Amarillo'), ('5', 'Azul')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('3', 'Redondo'), ('1', 'Cuadrado'), ('4', 'Corazón'), ('2', 'Rectangular')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('3', 'Cartel'), ('2', 'Arcos'), ('7', 'Base'), ('6', 'Cubiertos'), ('4', 'Piñata'), ('1', 'Globos'), ('5', 'Centro de mesa')], max_length=50),
        ),
    ]
