# Generated by Django 5.0.6 on 2024-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0026_evento_idarco_alter_globos_colorglobos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinata',
            options={'ordering': ['idpinata'], 'verbose_name': 'Pinata', 'verbose_name_plural': 'Pinatas'},
        ),
        migrations.RemoveField(
            model_name='cartel',
            name='personalizacion',
        ),
        migrations.RemoveField(
            model_name='cartel',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='idcartel',
        ),
        migrations.RemoveField(
            model_name='globos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pinata',
            name='tematica',
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidadglobos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='personalizacioncartel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tamanocartel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tematicapinata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('1', 'Blanco'), ('2', 'Rojo'), ('9', 'Marrón'), ('10', 'Gris'), ('8', 'Púrpura'), ('4', 'Amarillo'), ('3', 'Verde'), ('6', 'Naranja'), ('11', 'Negro'), ('5', 'Azul'), ('7', 'Rosa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('4', 'Extragrande'), ('2', 'Mediano'), ('3', 'Grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('7', 'Julio'), ('2', 'Febrero'), ('3', 'Marzo'), ('12', 'Diciembre'), ('9', 'Septiembre'), ('1', 'Enero'), ('5', 'Mayo'), ('10', 'Octubre'), ('8', 'Agosto'), ('4', 'Abril'), ('11', 'Noviembre'), ('6', 'Junio')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Globos'), ('2', 'Flores'), ('3', 'Luminarias'), ('4', 'Tela')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Corazón'), ('3', 'Cilindro'), ('2', 'Cubo'), ('4', 'Cilindro medio')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Vasos'), ('2', 'Platos'), ('3', 'Servilletas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('6', 'Aniversario de boda'), ('8', 'Día San Valentín'), ('5', 'Graduación'), ('1', 'Cumpleaños'), ('9', 'Compromiso'), ('2', 'Boda'), ('4', 'Baby shawers'), ('3', 'Revelación de sexo'), ('7', '14 de febrero'), ('10', 'Personalizada')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('1', 'Blanco'), ('2', 'Rojo'), ('9', 'Marrón'), ('10', 'Gris'), ('8', 'Púrpura'), ('4', 'Amarillo'), ('3', 'Verde'), ('6', 'Naranja'), ('11', 'Negro'), ('5', 'Azul'), ('7', 'Rosa')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('3', 'Redondo'), ('2', 'Rectangular'), ('1', 'Cuadrado'), ('4', 'Corazón')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('5', 'Centro de mesa'), ('1', 'Globos'), ('3', 'Cartel'), ('7', 'Base'), ('4', 'Piñata'), ('2', 'Arcos'), ('6', 'Cubiertos')], max_length=50),
        ),
    ]
