# Generated by Django 5.0.6 on 2024-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0027_alter_pinata_options_remove_cartel_personalizacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartel',
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('5', 'Azul'), ('10', 'Gris'), ('8', 'Púrpura'), ('9', 'Marrón'), ('2', 'Rojo'), ('7', 'Rosa'), ('4', 'Amarillo'), ('6', 'Naranja'), ('3', 'Verde'), ('11', 'Negro'), ('1', 'Blanco')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('2', 'Mediano'), ('4', 'Extragrande'), ('3', 'Grande')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('6', 'Junio'), ('1', 'Enero'), ('4', 'Abril'), ('5', 'Mayo'), ('2', 'Febrero'), ('7', 'Julio'), ('9', 'Septiembre'), ('3', 'Marzo'), ('10', 'Octubre'), ('8', 'Agosto'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Luminarias'), ('1', 'Globos'), ('2', 'Flores'), ('4', 'Tela')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('4', 'Cilindro medio'), ('3', 'Cilindro'), ('1', 'Corazón'), ('2', 'Cubo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Dulces'), ('1', 'Adornos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Platos'), ('1', 'Vasos'), ('3', 'Servilletas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('6', 'Aniversario de boda'), ('10', 'Personalizada'), ('2', 'Boda'), ('8', 'Día San Valentín'), ('1', 'Cumpleaños'), ('3', 'Revelación de sexo'), ('5', 'Graduación'), ('9', 'Compromiso'), ('7', '14 de febrero'), ('4', 'Baby shawers')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('5', 'Azul'), ('10', 'Gris'), ('8', 'Púrpura'), ('9', 'Marrón'), ('2', 'Rojo'), ('7', 'Rosa'), ('4', 'Amarillo'), ('6', 'Naranja'), ('3', 'Verde'), ('11', 'Negro'), ('1', 'Blanco')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('4', 'Corazón'), ('1', 'Cuadrado'), ('2', 'Rectangular'), ('3', 'Redondo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('7', 'Base'), ('3', 'Cartel'), ('1', 'Globos'), ('6', 'Cubiertos'), ('4', 'Piñata'), ('2', 'Arcos'), ('5', 'Centro de mesa')], max_length=50),
        ),
    ]
