# Generated by Django 5.0.6 on 2024-06-12 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globos', '0028_delete_cartel_alter_globos_colorglobos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='idcontrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='idpersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globos.persona'),
        ),
        migrations.AlterField(
            model_name='globos',
            name='colorglobos',
            field=models.CharField(choices=[('7', 'Rosa'), ('10', 'Gris'), ('3', 'Verde'), ('9', 'Marrón'), ('1', 'Blanco'), ('8', 'Púrpura'), ('11', 'Negro'), ('4', 'Amarillo'), ('5', 'Azul'), ('2', 'Rojo'), ('6', 'Naranja')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globos',
            name='formaglobos',
            field=models.CharField(choices=[('1', 'Chiquito'), ('4', 'Extragrande'), ('3', 'Grande'), ('2', 'Mediano')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='descripcion',
            field=models.CharField(choices=[('8', 'Agosto'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('10', 'Octubre'), ('2', 'Febrero'), ('9', 'Septiembre'), ('1', 'Enero'), ('11', 'Noviembre'), ('12', 'Diciembre'), ('6', 'Junio'), ('7', 'Julio')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='narco',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Luminarias'), ('4', 'Tela'), ('2', 'Flores'), ('1', 'Globos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nbase',
            name='descripcion',
            field=models.CharField(choices=[('2', 'Cubo'), ('3', 'Cilindro'), ('4', 'Cilindro medio'), ('1', 'Corazón')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncentromesa',
            name='descripcion',
            field=models.CharField(choices=[('1', 'Adornos'), ('2', 'Dulces')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ncubiertos',
            name='descripcion',
            field=models.CharField(choices=[('3', 'Servilletas'), ('2', 'Platos'), ('1', 'Vasos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ntematica',
            name='descripcion',
            field=models.CharField(choices=[('10', 'Personalizada'), ('3', 'Revelación de sexo'), ('2', 'Boda'), ('6', 'Aniversario de boda'), ('5', 'Graduación'), ('4', 'Baby shawers'), ('9', 'Compromiso'), ('1', 'Cumpleaños'), ('8', 'Día San Valentín'), ('7', '14 de febrero')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='colorpinata',
            field=models.CharField(choices=[('7', 'Rosa'), ('10', 'Gris'), ('3', 'Verde'), ('9', 'Marrón'), ('1', 'Blanco'), ('8', 'Púrpura'), ('11', 'Negro'), ('4', 'Amarillo'), ('5', 'Azul'), ('2', 'Rojo'), ('6', 'Naranja')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pinata',
            name='formapinata',
            field=models.CharField(choices=[('4', 'Corazón'), ('3', 'Redondo'), ('1', 'Cuadrado'), ('2', 'Rectangular')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProd',
            field=models.CharField(choices=[('4', 'Piñata'), ('7', 'Base'), ('6', 'Cubiertos'), ('1', 'Globos'), ('2', 'Arcos'), ('3', 'Cartel'), ('5', 'Centro de mesa')], max_length=50),
        ),
    ]
